---
- hosts: iosxe
  name: Clean up Lab
  connection: network_cli
  gather_facts: False

  tasks:

  - set_fact:
      ansible_connection: local

  - name: Remove NTP server 10.111.{{pod_number}}.66 with NETCONF
    netconf_config:
      content: |
          <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
              <ntp>
                <server xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ntp">
                  <server-list operation="delete">
                    <ip-address>10.111.{{pod_number}}.66</ip-address>
                  </server-list>
                </server>
              </ntp>
            </native>
          </config>
    ignore_errors: True
    failed_when: false


  - name: Delete a loopback with NETCONF
    netconf_config:
      content: |
          <config>
            <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
              <interface operation="delete">
                <name>Loopback1{{pod_number}}</name>
              </interface>
            </interfaces>
          </config>
    ignore_errors: True
    failed_when: false

