#simple IOS config in ansible
---
- hosts: iosxe
  name: Sample IOS config for Ansible
  connection: network_cli
  tasks:
    - name: Gather facts
      ios_facts:
        gather_subset: hardware

    - name: Display current IOS version
      debug:
        var: ansible_net_version

    - name: Run show ip int brief command
      ios_command:
        commands: show ip interface brief
      register: myint

    - name: Display value of "myint" variable
      debug:
        var: myint["stdout_lines"][0]

  ## Lab 1
    - name: Run show users
      ios_command:
        commands: show users
      register: shuser

    - name: Display value of "shuser" variable
      debug:
        var: shuser["stdout_lines"][0]

