#simple IOS config in ansible
---
- hosts: iosxe
  name: Sample IOS show ntp for Ansible
  connection: network_cli
  tasks:
  - name: run show ntp associations
    ios_command:
      commands: show ntp associations
    register: myntp

  - name: display value of "myntp" variable
    debug:
      var: myntp["stdout_lines"][0]


